### ISSUE TITLE
ERRO 403

### ISSUE THREAD

**Issue by deivison01** [olivsec/opencti-connectors#1]
Olá, tudo bem?

Segui todos os passos para realizar a integração do connector no OpenCTI, mas sempre dá erro 403 e não gera o token.

ERRO LOG:

[_opencti_lobo_guara_connector.1.43.txt](https://github.com/user-attachments/files/17559371/_opencti_lobo_guara_connector.1.43.txt)

**Comment by olivsec** [comment]
Estou corrigindo e aperfeiçoando o connector do OpenCTI. O mecanismo de token da API do Lobo Guará foi alterado, portanto, tenho que fazer essa alteração no connector também. Em alguns dias irei atualizar o connector e irei informar sobre a atualização no LinkedIn do Lobo Guará, além de inserir um vídeo no canal do youtube mostrando como implementar o connector no OpenCTI.

Deixarei a issue aberta aqui e assim que eu atualizar o código eu aviso aqui nessa issue.

**Comment by olivsec** [comment]
O connector foi atualizado e testado. Atualizei o código aqui no GitHub e já criei uma nova imagem no Docker Hub.

O docker-compose.yml já está pronto para baixar a imagem mais nova do Docker Hub, precisando apenas inserir o valor de algumas variáveis do arquivo.
